<?php
/**
 * Buildout API helpers.
 */

function np_process_buildout_item( $data = null ) {
	$result = array();
	$result['post_title'] 	= $data->name ?? '';
	$result['post_content'] = $data->description ?? '';
	$result['post_excerpt'] = $data->location_description ?? '';
	$result['post_status'] 	= 'publish';
	$result['post_type'] 		= 'tsc_property';
	
	$result['tax_input'] 		= array();
	$result['meta_input'] 	= np_process_buildout_item_meta( $data );

	// defined('WP_CLI') && WP_CLI::log(print_r(array_keys((array) $data), 1));
	return $result;
}

function np_process_buildout_item_meta( $data = null ) {
	$checksum = md5( json_encode( $data ) );
	$result = array(
		'_import_buildout_id' 			=> np_generate_buildout_item_id( $data ),
		'_import_from' 							=> 'buildout',
		'_import_buildout_checksum' => $checksum,
	);

	$props = array(
		'id',
		'broker_id',
		'second_broker_id',
		'third_broker_id',
		'broker_ids',
		'address',
		'city',
		'state',
		'zip',
		'county',
		'country_code',
		'country_name',
		'hide_address',
		'hide_address_label_override',
		'market',
		'submarket',
		'cross_streets',
		'location_description',
		'latitude',
		'longitude',
		'custom_lat_lng',
		'name',
		'property_type_id',
		'property_type_label_override',
		'property_subtype_id',
		'additional_property_subtype_ids',
		'apn',
		'zoning',
		'lot_size_acres',
		'you_tube_url',
		'mls_id',
		'ceiling_height_f',
		'ceiling_height_min',
		'renovated',
		'parking_ratio',
		'number_of_parking_spaces',
		'utilities_description',
		'traffic_count',
		'traffic_count_street',
		'traffic_count_frontage',
		'site_description',
		'grade_level_doors',
		'dock_high_doors',
		'number_of_cranes',
		'sprinkler_description',
		'power_description',
		'industrial_office_space',
		'display_locale_override',
		'currency_key',
		'currency_format',
		'measurements',
		'building_size_sf',
		'number_of_units',
		'number_of_floors',
		'year_built',
		'occupancy_pct',
		'building_class',
		'gross_leasable_area',
		'proposal',
		'sale',
		'sale_deal_status_id',
		'auction',
		'auction_date',
		'auction_time',
		'auction_location',
		'auction_starting_bid_dollars',
		'auction_url',
		'distressed',
		'hide_sale_price',
		'hidden_price_label',
		'sale_price_dollars',
		'sale_price_per_unit',
		'sale_price_units',
		'sale_title',
		'sale_description',
		'sale_expiration_date',
		'sale_bullets',
		'sale_pdf_url',
		'property_use_id',
		'tenancy_id',
		'cap_rate_pct',
		'net_operating_income',
		'land_legal_description',
		'parking_type_id',
		'elevators',
		'sprinklers',
		'construction_status_id',
		'walls',
		'roof',
		'crane_description',
		'taxes',
		'frontage',
		'lot_depth',
		'number_of_buildings',
		'number_of_lots',
		'best_use',
		'irrigation',
		'irrigation_description',
		'water',
		'water_description',
		'telephone',
		'telephone_description',
		'cable',
		'cable_description',
		'gas',
		'gas_description',
		'sewer',
		'environmental_issues',
		'topography',
		'soil_type',
		'easements_description',
		'foundation',
		'framing',
		'exterior_description',
		'hvac',
		'parking_description',
		'landscaping',
		'rail_access',
		'column_space',
		'dock_door_description',
		'drive_in_bays',
		'trailer_parking',
		'amenities',
		'days_on_market',
		'lease',
		'lease_deal_status_ids',
		'lease_title',
		'lease_description',
		'lease_bullets',
		'lease_pdf_url',
		'lease_expiration_date',
		'leed_certified',
		'photos',
		'documents',
		'matterport_url',
		'sale_listing_url',
		'sale_listing_published',
		'sale_listing_searchable',
		'sale_listing_slug',
		'sale_listing_web_title',
		'sale_listing_web_description',
		'lease_listing_url',
		'lease_listing_published',
		'lease_listing_searchable',
		'lease_listing_slug',
		'lease_listing_web_title',
		'lease_listing_web_description',
		'draft',
		'notes',
		'external_id',
		'gross_scheduled_income',
		'other_income',
		'operating_expenses',
		'vacancy_cost',
		'down_payment',
		'cash_on_cash',
		'total_return',
		'debt_service',
		'principal_reduction_yr_1',
		'rev_par',
		'adr',
		'nearest_highway',
		'load_factor',
		'restrooms',
		'mapright_embed_code',
		'custom_fields',
		'created_at',
		'updated_at',
	);
		
	foreach( $props as $prop ) {
		$key = '_buildout_' . $prop;
		$result[ $key ] = $data->$prop ?? '';
	}

	return array_filter($result);
}

function np_generate_buildout_item_id( $data = null ) {
	return (int) $data->id;
}